# Google Cloud Build configuration for CI/CD
# This file automates building and deploying your frontend app to Cloud Run
#
# Usage:
#   gcloud builds submit --config=cloudbuild.yaml --project=YOUR_PROJECT_ID
#
# Note: PROJECT_ID, BUILD_ID, and other variables are automatically provided by Cloud Build

steps:
  # Step 1: Build the Docker image with Vite build arguments
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "VITE_API_URL=${_VITE_API_URL}",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${BUILD_ID}",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:latest",
        ".",
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}",
      ]

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${BUILD_ID}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
      ]

# Substitution variables (should match your terraform configuration in /terraform)
# IMPORTANT: Update _VITE_API_URL with your backend URL from: terraform output backend_api_url
substitutions:
  _REGION: europe-west1
  _SERVICE_NAME: ad4screen-frontend-service
  _ARTIFACT_REPO: ad4screen-aso-repo
  _VITE_API_URL: https://ad4screen-api-service-170914171653.europe-west1.run.app # Get from: cd terraform && terraform output -raw backend_api_url

# Build configuration
options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: 1200s

# Images to be stored in Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${BUILD_ID}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:latest"
